// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datapoints/server/data_point_processors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/datapoints/server/data_point_processors.proto</summary>
  public static partial class DataPointProcessorsReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/datapoints/server/data_point_processors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointProcessorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkFkb2xpdHRsZS90aW1lc2VyaWVzL2RhdGFwb2ludHMvc2VydmVyL2RhdGFf",
            "cG9pbnRfcHJvY2Vzc29ycy5wcm90bxIlZG9saXR0bGUudGltZXNlcmllcy5k",
            "YXRhcG9pbnRzLnNlcnZlchouZG9saXR0bGUvdGltZXNlcmllcy9kYXRhdHlw",
            "ZXMvZGF0YV9wb2ludC5wcm90bxpAZG9saXR0bGUvdGltZXNlcmllcy9kYXRh",
            "cG9pbnRzL3NlcnZlci9kYXRhX3BvaW50X3Byb2Nlc3Nvci5wcm90bzKGAQoT",
            "RGF0YVBvaW50UHJvY2Vzc29ycxJvCgRPcGVuEjkuZG9saXR0bGUudGltZXNl",
            "cmllcy5kYXRhcG9pbnRzLnNlcnZlci5EYXRhUG9pbnRQcm9jZXNzb3IaKC5k",
            "b2xpdHRsZS50aW1lc2VyaWVzLmRhdGF0eXBlcy5EYXRhUG9pbnQiADABQjWq",
            "AjJEb2xpdHRsZS5UaW1lU2VyaWVzLlJ1bnRpbWUuRGF0YVBvaW50cy5HcnBj",
            "LlNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.DataPointProcessorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
