// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datapoints/server/data_point_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/datapoints/server/data_point_stream.proto</summary>
  public static partial class DataPointStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/datapoints/server/data_point_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1kb2xpdHRsZS90aW1lc2VyaWVzL2RhdGFwb2ludHMvc2VydmVyL2RhdGFf",
            "cG9pbnRfc3RyZWFtLnByb3RvEiVkb2xpdHRsZS50aW1lc2VyaWVzLmRhdGFw",
            "b2ludHMuc2VydmVyGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aLmRv",
            "bGl0dGxlL3RpbWVzZXJpZXMvZGF0YXR5cGVzL2RhdGFfcG9pbnQucHJvdG8y",
            "XwoPRGF0YVBvaW50U3RyZWFtEkwKBE9wZW4SKC5kb2xpdHRsZS50aW1lc2Vy",
            "aWVzLmRhdGF0eXBlcy5EYXRhUG9pbnQaFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkiACgBQjWqAjJEb2xpdHRsZS5UaW1lU2VyaWVzLlJ1bnRpbWUuRGF0YVBv",
            "aW50cy5HcnBjLlNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
