// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datapoints/server/input_stream.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {
  /// <summary>
  /// Represents the service for datapoint input stream 
  /// </summary>
  public static partial class InputStream
  {
    static readonly string __ServiceName = "dolittle.timeseries.datapoints.server.InputStream";

    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint> __Marshaller_dolittle_timeseries_datatypes_DataPoint = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie> __Marshaller_dolittle_timeseries_datapoints_server_TimeSerie = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie> __Method_Open = new grpc::Method<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Open",
        __Marshaller_dolittle_timeseries_datatypes_DataPoint,
        __Marshaller_dolittle_timeseries_datapoints_server_TimeSerie);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.InputStreamReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InputStream</summary>
    [grpc::BindServiceMethod(typeof(InputStream), "BindService")]
    public abstract partial class InputStreamBase
    {
      public virtual global::System.Threading.Tasks.Task Open(grpc::IAsyncStreamReader<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint> requestStream, grpc::IServerStreamWriter<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InputStream</summary>
    public partial class InputStreamClient : grpc::ClientBase<InputStreamClient>
    {
      /// <summary>Creates a new client for InputStream</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InputStreamClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InputStream that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InputStreamClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InputStreamClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InputStreamClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie> Open(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Open(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie> Open(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Open, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InputStreamClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InputStreamClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InputStreamBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Open, serviceImpl.Open).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, InputStreamBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Open, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPoint, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.TimeSerie>(serviceImpl.Open));
    }

  }
}
#endregion
