// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datapoints/server/output_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/datapoints/server/output_stream.proto</summary>
  public static partial class OutputStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/datapoints/server/output_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OutputStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjlkb2xpdHRsZS90aW1lc2VyaWVzL2RhdGFwb2ludHMvc2VydmVyL291dHB1",
            "dF9zdHJlYW0ucHJvdG8SJWRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50",
            "cy5zZXJ2ZXIaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxouZG9saXR0",
            "bGUvdGltZXNlcmllcy9kYXRhdHlwZXMvZGF0YV9wb2ludC5wcm90bzJcCgxP",
            "dXRwdXRTdHJlYW0STAoET3BlbhIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoo",
            "LmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXR5cGVzLkRhdGFQb2ludCIAMAFC",
            "NaoCMkRvbGl0dGxlLlRpbWVTZXJpZXMuUnVudGltZS5EYXRhUG9pbnRzLkdy",
            "cGMuU2VydmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
