// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/client/pull_connector.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc {
  /// <summary>
  /// Represents the service for working with connectors that are pull based
  /// </summary>
  public static partial class PullConnector
  {
    static readonly string __ServiceName = "dolittle.timeseries.connectors.client.PullConnector";

    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest> __Marshaller_dolittle_timeseries_connectors_client_PullRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult> __Marshaller_dolittle_timeseries_connectors_client_PullResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest, global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult> __Method_Pull = new grpc::Method<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest, global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pull",
        __Marshaller_dolittle_timeseries_connectors_client_PullRequest,
        __Marshaller_dolittle_timeseries_connectors_client_PullResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullConnectorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PullConnector</summary>
    [grpc::BindServiceMethod(typeof(PullConnector), "BindService")]
    public abstract partial class PullConnectorBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult> Pull(global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PullConnector</summary>
    public partial class PullConnectorClient : grpc::ClientBase<PullConnectorClient>
    {
      /// <summary>Creates a new client for PullConnector</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PullConnectorClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PullConnector that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PullConnectorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PullConnectorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PullConnectorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult Pull(global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pull(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult Pull(global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pull, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult> PullAsync(global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PullAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult> PullAsync(global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pull, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PullConnectorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PullConnectorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PullConnectorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Pull, serviceImpl.Pull).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PullConnectorBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Pull, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullRequest, global::Dolittle.TimeSeries.Runtime.Connectors.Client.Grpc.PullResult>(serviceImpl.Pull));
    }

  }
}
#endregion
