// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datatypes/coordinate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataTypes {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/datatypes/coordinate.proto</summary>
  public static partial class CoordinateReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/datatypes/coordinate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoordinateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5kb2xpdHRsZS90aW1lc2VyaWVzL2RhdGF0eXBlcy9jb29yZGluYXRlLnBy",
            "b3RvEh1kb2xpdHRsZS50aW1lc2VyaWVzLmRhdGF0eXBlcxovZG9saXR0bGUv",
            "dGltZXNlcmllcy9kYXRhdHlwZXMvbWVhc3VyZW1lbnQucHJvdG8iiQEKCkNv",
            "b3JkaW5hdGUSPQoJbG9uZ2l0dWRlGAEgASgLMiouZG9saXR0bGUudGltZXNl",
            "cmllcy5kYXRhdHlwZXMuTWVhc3VyZW1lbnQSPAoIbGF0aXR1ZGUYAiABKAsy",
            "Ki5kb2xpdHRsZS50aW1lc2VyaWVzLmRhdGF0eXBlcy5NZWFzdXJlbWVudEIg",
            "qgIdRG9saXR0bGUuVGltZVNlcmllcy5EYXRhVHlwZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.DataTypes.MeasurementReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.DataTypes.Coordinate), global::Dolittle.TimeSeries.DataTypes.Coordinate.Parser, new[]{ "Longitude", "Latitude" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Coordinate : pb::IMessage<Coordinate> {
    private static readonly pb::MessageParser<Coordinate> _parser = new pb::MessageParser<Coordinate>(() => new Coordinate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Coordinate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.DataTypes.CoordinateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Coordinate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Coordinate(Coordinate other) : this() {
      longitude_ = other.longitude_ != null ? other.longitude_.Clone() : null;
      latitude_ = other.latitude_ != null ? other.latitude_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Coordinate Clone() {
      return new Coordinate(this);
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 1;
    private global::Dolittle.TimeSeries.DataTypes.Measurement longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.TimeSeries.DataTypes.Measurement Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 2;
    private global::Dolittle.TimeSeries.DataTypes.Measurement latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.TimeSeries.DataTypes.Measurement Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Coordinate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Coordinate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Longitude, other.Longitude)) return false;
      if (!object.Equals(Latitude, other.Latitude)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (longitude_ != null) hash ^= Longitude.GetHashCode();
      if (latitude_ != null) hash ^= Latitude.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (longitude_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Longitude);
      }
      if (latitude_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Latitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (longitude_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Longitude);
      }
      if (latitude_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Latitude);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Coordinate other) {
      if (other == null) {
        return;
      }
      if (other.longitude_ != null) {
        if (longitude_ == null) {
          Longitude = new global::Dolittle.TimeSeries.DataTypes.Measurement();
        }
        Longitude.MergeFrom(other.Longitude);
      }
      if (other.latitude_ != null) {
        if (latitude_ == null) {
          Latitude = new global::Dolittle.TimeSeries.DataTypes.Measurement();
        }
        Latitude.MergeFrom(other.Latitude);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (longitude_ == null) {
              Longitude = new global::Dolittle.TimeSeries.DataTypes.Measurement();
            }
            input.ReadMessage(Longitude);
            break;
          }
          case 18: {
            if (latitude_ == null) {
              Latitude = new global::Dolittle.TimeSeries.DataTypes.Measurement();
            }
            input.ReadMessage(Latitude);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
