// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datapoints/client/data_point_processor.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client {
  /// <summary>
  /// Represents the client service for processing data points
  /// </summary>
  public static partial class DataPointProcessor
  {
    static readonly string __ServiceName = "dolittle.timeseries.datapoints.client.DataPointProcessor";

    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage> __Marshaller_dolittle_timeseries_datapoints_client_DataPointMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Process = new grpc::Method<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Process",
        __Marshaller_dolittle_timeseries_datapoints_client_DataPointMessage,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointProcessorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataPointProcessor</summary>
    [grpc::BindServiceMethod(typeof(DataPointProcessor), "BindService")]
    public abstract partial class DataPointProcessorBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Process(grpc::IAsyncStreamReader<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataPointProcessor</summary>
    public partial class DataPointProcessorClient : grpc::ClientBase<DataPointProcessorClient>
    {
      /// <summary>Creates a new client for DataPointProcessor</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DataPointProcessorClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataPointProcessor that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DataPointProcessorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DataPointProcessorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DataPointProcessorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage, global::Google.Protobuf.WellKnownTypes.Empty> Process(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Process(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage, global::Google.Protobuf.WellKnownTypes.Empty> Process(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Process, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DataPointProcessorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataPointProcessorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DataPointProcessorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Process, serviceImpl.Process).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataPointProcessorBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Process, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Client.DataPointMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Process));
    }

  }
}
#endregion
