// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/server/pull_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/connectors/server/pull_connectors.proto</summary>
  public static partial class PullConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/connectors/server/pull_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PullConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtkb2xpdHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMvc2VydmVyL3B1bGxf",
            "Y29ubmVjdG9ycy5wcm90bxIlZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0",
            "b3JzLnNlcnZlcho6ZG9saXR0bGUvdGltZXNlcmllcy9jb25uZWN0b3JzL3Nl",
            "cnZlci9wdWxsX2Nvbm5lY3Rvci5wcm90bxo7ZG9saXR0bGUvdGltZXNlcmll",
            "cy9jb25uZWN0b3JzL3NlcnZlci9yZWdpc3Rlcl9yZXN1bHQucHJvdG8yiwEK",
            "DlB1bGxDb25uZWN0b3JzEnkKCFJlZ2lzdGVyEjQuZG9saXR0bGUudGltZXNl",
            "cmllcy5jb25uZWN0b3JzLnNlcnZlci5QdWxsQ29ubmVjdG9yGjUuZG9saXR0",
            "bGUudGltZXNlcmllcy5jb25uZWN0b3JzLnNlcnZlci5SZWdpc3RlclJlc3Vs",
            "dCIAQjWqAjJEb2xpdHRsZS5UaW1lU2VyaWVzLlJ1bnRpbWUuQ29ubmVjdG9y",
            "cy5HcnBjLlNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.PullConnectorReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.RegisterResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
