// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/server/pull_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/connectors/server/pull_connectors.proto</summary>
  public static partial class PullConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/connectors/server/pull_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PullConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtkb2xpdHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMvc2VydmVyL3B1bGxf",
            "Y29ubmVjdG9ycy5wcm90bxIlZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0",
            "b3JzLnNlcnZlchobZ29vZ2xlL3Byb3RvYnVmL0VtcHR5LnByb3RvGjpkb2xp",
            "dHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMvc2VydmVyL3B1bGxfY29ubmVj",
            "dG9yLnByb3RvMmwKDlB1bGxDb25uZWN0b3JzEloKCFJlZ2lzdGVyEjQuZG9s",
            "aXR0bGUudGltZXNlcmllcy5jb25uZWN0b3JzLnNlcnZlci5QdWxsQ29ubmVj",
            "dG9yGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgBCNaoCMkRvbGl0dGxlLlRp",
            "bWVTZXJpZXMuUnVudGltZS5Db25uZWN0b3JzLkdycGMuU2VydmVyYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.PullConnectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
