// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/server/stream_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/connectors/server/stream_connectors.proto</summary>
  public static partial class StreamConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/connectors/server/stream_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StreamConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1kb2xpdHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMvc2VydmVyL3N0cmVh",
            "bV9jb25uZWN0b3JzLnByb3RvEiVkb2xpdHRsZS50aW1lc2VyaWVzLmNvbm5l",
            "Y3RvcnMuc2VydmVyGjxkb2xpdHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMv",
            "c2VydmVyL3N0cmVhbV9jb25uZWN0b3IucHJvdG8aO2RvbGl0dGxlL3RpbWVz",
            "ZXJpZXMvY29ubmVjdG9ycy9zZXJ2ZXIvcmVnaXN0ZXJfcmVzdWx0LnByb3Rv",
            "Mo8BChBTdHJlYW1Db25uZWN0b3JzEnsKCFJlZ2lzdGVyEjYuZG9saXR0bGUu",
            "dGltZXNlcmllcy5jb25uZWN0b3JzLnNlcnZlci5TdHJlYW1Db25uZWN0b3Ia",
            "NS5kb2xpdHRsZS50aW1lc2VyaWVzLmNvbm5lY3RvcnMuc2VydmVyLlJlZ2lz",
            "dGVyUmVzdWx0IgBCNaoCMkRvbGl0dGxlLlRpbWVTZXJpZXMuUnVudGltZS5D",
            "b25uZWN0b3JzLkdycGMuU2VydmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.StreamConnectorReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.RegisterResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
