// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull_connectors.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc {

  /// <summary>Holder for reflection information generated from pull_connectors.proto</summary>
  public static partial class PullConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for pull_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PullConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwdWxsX2Nvbm5lY3RvcnMucHJvdG8SHmRvbGl0dGxlLnRpbWVzZXJpZXMu",
            "Y29ubmVjdG9ycxodcHVsbF9jb25uZWN0b3JfZ2V0X2RhdGEucHJvdG8aGXB1",
            "bGxfY29ubmVjdG9yX2RhdGEucHJvdG8yiwEKDlB1bGxDb25uZWN0b3JzEnkK",
            "CFJlZ2lzdGVyEjQuZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0b3JzLlB1",
            "bGxDb25uZWN0b3JHZXREYXRhGjEuZG9saXR0bGUudGltZXNlcmllcy5jb25u",
            "ZWN0b3JzLlB1bGxDb25uZWN0b3JEYXRhIgAoATABQi6qAitEb2xpdHRsZS5U",
            "aW1lU2VyaWVzLlJ1bnRpbWUuQ29ubmVjdG9ycy5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetDataReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
