// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/pull_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/connectors/pull_connectors.proto</summary>
  public static partial class PullConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/connectors/pull_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PullConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRkb2xpdHRsZS90aW1lc2VyaWVzL2Nvbm5lY3RvcnMvcHVsbF9jb25uZWN0",
            "b3JzLnByb3RvEh5kb2xpdHRsZS50aW1lc2VyaWVzLmNvbm5lY3RvcnMaPGRv",
            "bGl0dGxlL3RpbWVzZXJpZXMvY29ubmVjdG9ycy9wdWxsX2Nvbm5lY3Rvcl9n",
            "ZXRfZGF0YS5wcm90bxo4ZG9saXR0bGUvdGltZXNlcmllcy9jb25uZWN0b3Jz",
            "L3B1bGxfY29ubmVjdG9yX2RhdGEucHJvdG8yiwEKDlB1bGxDb25uZWN0b3Jz",
            "EnkKCFJlZ2lzdGVyEjQuZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0b3Jz",
            "LlB1bGxDb25uZWN0b3JHZXREYXRhGjEuZG9saXR0bGUudGltZXNlcmllcy5j",
            "b25uZWN0b3JzLlB1bGxDb25uZWN0b3JEYXRhIgAoATABQi6qAitEb2xpdHRs",
            "ZS5UaW1lU2VyaWVzLlJ1bnRpbWUuQ29ubmVjdG9ycy5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetDataReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
