// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/connectors/pull_connectors.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc {
  /// <summary>
  /// Represents the service for working with connectors that are pull based
  /// </summary>
  public static partial class PullConnectors
  {
    static readonly string __ServiceName = "dolittle.timeseries.connectors.PullConnectors";

    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData> __Marshaller_dolittle_timeseries_connectors_PullConnectorGetData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData> __Marshaller_dolittle_timeseries_connectors_PullConnectorData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData> __Method_Register = new grpc::Method<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Register",
        __Marshaller_dolittle_timeseries_connectors_PullConnectorGetData,
        __Marshaller_dolittle_timeseries_connectors_PullConnectorData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PullConnectors</summary>
    [grpc::BindServiceMethod(typeof(PullConnectors), "BindService")]
    public abstract partial class PullConnectorsBase
    {
      public virtual global::System.Threading.Tasks.Task Register(grpc::IAsyncStreamReader<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData> requestStream, grpc::IServerStreamWriter<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PullConnectors</summary>
    public partial class PullConnectorsClient : grpc::ClientBase<PullConnectorsClient>
    {
      /// <summary>Creates a new client for PullConnectors</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PullConnectorsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PullConnectors that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PullConnectorsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PullConnectorsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PullConnectorsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData> Register(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Register(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData> Register(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Register, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PullConnectorsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PullConnectorsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PullConnectorsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Register, serviceImpl.Register).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PullConnectorsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Register, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorGetData, global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.PullConnectorData>(serviceImpl.Register));
    }

  }
}
#endregion
