// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/timeseries/datatypes/value.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataTypes.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/timeseries/datatypes/value.proto</summary>
  public static partial class ValueReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/timeseries/datatypes/value.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilkb2xpdHRsZS90aW1lc2VyaWVzL2RhdGF0eXBlcy92YWx1ZS5wcm90bxId",
            "ZG9saXR0bGUudGltZXNlcmllcy5kYXRhdHlwZXMaL2RvbGl0dGxlL3RpbWVz",
            "ZXJpZXMvZGF0YXR5cGVzL21lYXN1cmVtZW50LnByb3RvGitkb2xpdHRsZS90",
            "aW1lc2VyaWVzL2RhdGF0eXBlcy92ZWN0b3IyLnByb3RvGitkb2xpdHRsZS90",
            "aW1lc2VyaWVzL2RhdGF0eXBlcy92ZWN0b3IzLnByb3RvItsBCgVWYWx1ZRJH",
            "ChFtZWFzdXJlbWVudF92YWx1ZRgBIAEoCzIqLmRvbGl0dGxlLnRpbWVzZXJp",
            "ZXMuZGF0YXR5cGVzLk1lYXN1cmVtZW50SAASPwoNdmVjdG9yMl92YWx1ZRgC",
            "IAEoCzImLmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXR5cGVzLlZlY3RvcjJI",
            "ABI/Cg12ZWN0b3IzX3ZhbHVlGAMgASgLMiYuZG9saXR0bGUudGltZXNlcmll",
            "cy5kYXRhdHlwZXMuVmVjdG9yM0gAQgcKBXZhbHVlQimqAiZEb2xpdHRsZS5U",
            "aW1lU2VyaWVzLkRhdGFUeXBlcy5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.DataTypes.Protobuf.MeasurementReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2Reflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.DataTypes.Protobuf.Value), global::Dolittle.TimeSeries.DataTypes.Protobuf.Value.Parser, new[]{ "MeasurementValue", "Vector2Value", "Vector3Value" }, new[]{ "Value" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Value : pb::IMessage<Value> {
    private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Value> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.DataTypes.Protobuf.ValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value(Value other) : this() {
      switch (other.ValueCase) {
        case ValueOneofCase.MeasurementValue:
          MeasurementValue = other.MeasurementValue.Clone();
          break;
        case ValueOneofCase.Vector2Value:
          Vector2Value = other.Vector2Value.Clone();
          break;
        case ValueOneofCase.Vector3Value:
          Vector3Value = other.Vector3Value.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value Clone() {
      return new Value(this);
    }

    /// <summary>Field number for the "measurement_value" field.</summary>
    public const int MeasurementValueFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.TimeSeries.DataTypes.Protobuf.Measurement MeasurementValue {
      get { return valueCase_ == ValueOneofCase.MeasurementValue ? (global::Dolittle.TimeSeries.DataTypes.Protobuf.Measurement) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.MeasurementValue;
      }
    }

    /// <summary>Field number for the "vector2_value" field.</summary>
    public const int Vector2ValueFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2 Vector2Value {
      get { return valueCase_ == ValueOneofCase.Vector2Value ? (global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.Vector2Value;
      }
    }

    /// <summary>Field number for the "vector3_value" field.</summary>
    public const int Vector3ValueFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3 Vector3Value {
      get { return valueCase_ == ValueOneofCase.Vector3Value ? (global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.Vector3Value;
      }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      MeasurementValue = 1,
      Vector2Value = 2,
      Vector3Value = 3,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Value);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Value other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MeasurementValue, other.MeasurementValue)) return false;
      if (!object.Equals(Vector2Value, other.Vector2Value)) return false;
      if (!object.Equals(Vector3Value, other.Vector3Value)) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (valueCase_ == ValueOneofCase.MeasurementValue) hash ^= MeasurementValue.GetHashCode();
      if (valueCase_ == ValueOneofCase.Vector2Value) hash ^= Vector2Value.GetHashCode();
      if (valueCase_ == ValueOneofCase.Vector3Value) hash ^= Vector3Value.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (valueCase_ == ValueOneofCase.MeasurementValue) {
        output.WriteRawTag(10);
        output.WriteMessage(MeasurementValue);
      }
      if (valueCase_ == ValueOneofCase.Vector2Value) {
        output.WriteRawTag(18);
        output.WriteMessage(Vector2Value);
      }
      if (valueCase_ == ValueOneofCase.Vector3Value) {
        output.WriteRawTag(26);
        output.WriteMessage(Vector3Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (valueCase_ == ValueOneofCase.MeasurementValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeasurementValue);
      }
      if (valueCase_ == ValueOneofCase.Vector2Value) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector2Value);
      }
      if (valueCase_ == ValueOneofCase.Vector3Value) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector3Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Value other) {
      if (other == null) {
        return;
      }
      switch (other.ValueCase) {
        case ValueOneofCase.MeasurementValue:
          if (MeasurementValue == null) {
            MeasurementValue = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Measurement();
          }
          MeasurementValue.MergeFrom(other.MeasurementValue);
          break;
        case ValueOneofCase.Vector2Value:
          if (Vector2Value == null) {
            Vector2Value = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2();
          }
          Vector2Value.MergeFrom(other.Vector2Value);
          break;
        case ValueOneofCase.Vector3Value:
          if (Vector3Value == null) {
            Vector3Value = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3();
          }
          Vector3Value.MergeFrom(other.Vector3Value);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Dolittle.TimeSeries.DataTypes.Protobuf.Measurement subBuilder = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Measurement();
            if (valueCase_ == ValueOneofCase.MeasurementValue) {
              subBuilder.MergeFrom(MeasurementValue);
            }
            input.ReadMessage(subBuilder);
            MeasurementValue = subBuilder;
            break;
          }
          case 18: {
            global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2 subBuilder = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector2();
            if (valueCase_ == ValueOneofCase.Vector2Value) {
              subBuilder.MergeFrom(Vector2Value);
            }
            input.ReadMessage(subBuilder);
            Vector2Value = subBuilder;
            break;
          }
          case 26: {
            global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3 subBuilder = new global::Dolittle.TimeSeries.DataTypes.Protobuf.Vector3();
            if (valueCase_ == ValueOneofCase.Vector3Value) {
              subBuilder.MergeFrom(Vector3Value);
            }
            input.ReadMessage(subBuilder);
            Vector3Value = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
